package wtf.casper.storageapi;

public enum FilterType {
    NOT_ENDS_WITH, STARTS_WITH, NOT_STARTS_WITH, CONTAINS, NOT_CONTAINS, LESS_THAN, NOT_GREATER_THAN_OR_EQUAL_TO, EQUALS, GREATER_THAN, NOT_LESS_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO, NOT_GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, NOT_LESS_THAN, NOT_EQUALS, ENDS_WITH

}
